# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kanta API - Production
    url: https://app.kanta.fr/api
  - name: Kanta Front - Production
    url: https://app.kanta.fr
  - name: Kanta API - Preprod
    url: https://preprod.kanta.fr/api
  - name: Kanta Front - Preprod
    url: https://preprod.kanta.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: pierrelepetit.com
  # baseUrl: /your-repo-name
  logoUrl: https://kanta.fr/assets/images/logo-beta.svg
  name: Kanta
  introTitle: "**Kanta** Status Page"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
