# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kanta API - Production
    url: https://app.kanta.fr/api
    expectedStatusCodes:
      - 404
  - name: Kanta Front - Production
    url: https://app.kanta.fr
  - name: Kanta API - Preprod
    url: https://preprod.kanta.fr/api
    expectedStatusCodes:
      - 404
  - name: Kanta Front - Preprod
    url: https://preprod.kanta.fr

status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: pierrelepetit.com
  baseUrl: /kanta-uptime
  logoUrl: https://kanta.fr/assets/images/logo-beta.svg
  name: Kanta
  introTitle: "**Kanta** Status Page"
  introMessage: ""
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
